---

- name: Install xfce4 xfce4-goodies
  ansible.builtin.apt:
   update_cache: yes
   name:
    - xfce4
    - xfce4-goodies

- name: Install common desktop packages
  ansible.builtin.apt:
   name:
    - keepassxc
    - qpdfview
    - ristretto
    - mousepad
    - doublecmd-gtk
    - thunderbird
    - k3b
    - gitk

# no longer install chromium as it's outdated on debian
- name: Install browser packages
  ansible.builtin.apt:
   name:
    - firefox-esr

- name: Install utility packages
  ansible.builtin.apt:
   name:
    - firejail
    - gnome-disk-utility
    - xclip
    - lvm2
    - ntfs-3g
    - p7zip
    - p7zip-full
    - unrar
    - scrot
    - gparted
    - apt-file
    - vim
    - gvfs-fuse
    # required for borg 1.1 now?
    - python3-llfuse
    - locales

- name: Install networking packages
  ansible.builtin.apt:
   name:
    - freerdp2-x11
    - openssh-server
    - openssh-client
    - network-manager-gnome

- name: Install automation packages
  ansible.builtin.apt:
   name:
    - libssl-dev
    # https://github.com/MeetMe/newrelic-plugin-agent/issues/151
    - python3-dev
    # required for virtualenvs for ansible
    - gcc
    # required for molecule vagrant/libvirt
    - vagrant-libvirt

- name: Install media related packages
  ansible.builtin.apt:
   name:
    - vlc
    - smplayer
    - mpv
    - youtube-dl
    - pavucontrol

- name: Install printing related packages
  ansible.builtin.apt:
   name:
    - cups
    - xsane

- name: Install libreoffice
  ansible.builtin.apt:
   name:
    - libreoffice
    - libreoffice-style-colibre
    - libreoffice-style-elementary
    - libreoffice-style-karasa-jaga
    - libreoffice-style-sifr
    - libreoffice-style-sukapura
   # needs the extra packages from recommends otherwise
   # some sheets looks awful
   install_recommends: 'yes'

- name: Install image and video editing related packages
  ansible.builtin.apt:
   name:
    - obs-studio
    - krita
    - gimp
    - kolourpaint4

- name: Install KVM/qemu packages with virt-manager
  ansible.builtin.apt:
   name:
    - virt-manager
    - libvirt-daemon
    # ovmf provides support for uefi booting vm-s
    # useful for gpu passthrough
    - ovmf

- name: Add user to libvirt group
  ansible.builtin.user:
   name: "{{ user }}"
   groups: libvirt
   append: yes
   shell: /bin/bash
   state: present

- name: Disable libreoffice logo and eula display
  ansible.builtin.template:
   src: templates/sofficerc.j2
   dest: /etc/libreoffice/sofficerc
   owner: root
   group: root
   mode: 0644
   backup: yes

# systemd boot/shutdown timeout settings
- name: Systemd boot/shutdown timeout settings
  ansible.builtin.template:
   src: templates/system.conf.j2
   dest: /etc/systemd/system.conf
   owner: root
   group: root
   mode: 0644
   backup: yes

# network config
- name: Create blank network interfaces file with backup
  ansible.builtin.copy:
   src: files/interfaces.conf
   dest: /etc/network/interfaces
   owner: root
   group: root
   mode: 0644
   backup: yes

# conf locales
- name: Template /etc/locale.gen
  ansible.builtin.template:
   src: templates/locale.gen.j2
   dest: /etc/locale.gen
   owner: root
   group: root
   mode: 0644
  register: locale_gen
  notify: locale-gen
