---
- name: install non-free software for desktop
  apt:
   name:
    - firmware-amd-graphics
    - intel-microcode
    - unrar

- name: create vfio.conf for gpu pass through
  template:
   src: templates/vfio_gpu.j2
   dest: /etc/modprobe.d/vfio.conf
   owner: root
   group: root
   mode: 0644
  register: vfio_result
  notify: "update-initframs"

# Add vfio modules to initrd
# so vfio mod can grab the vid card in time before amdgpu
- name: Add vfio modules to initrd
  template:
   src: templates/initframs-modules.j2
   dest: /etc/initramfs-tools/modules
   owner: root
   group: root
   mode: 0644
  register: initframs_results
  notify: "update-initframs"
