---
- name: install non-free software for desktop
  apt:
   name: "{{ packages }}"
  vars:
   packages:
   - firmware-amd-graphics
   - intel-microcode
   - unrar

- name: create vfio.conf for gpu pass through
  template:
   src: templates/vfio_gpu.j2
   dest: /etc/modprobe.d/vfio.conf
   owner: root
   group: root
   mode: 0644
   backup: yes
  register: vfio_result

# then run update-grub
- name: run command update-grub
  command: update-grub
  # skip for docker ct as there's no point in running
  # update-grub in there
  when: ansible_virtualization_type != "docker" and vfio_result.changed

# Add vfio modules to initrd
# so vfio mod can grab the vid card in time before amdgpu
- name: Add vfio modules to initrd
  template:
   src: templates/initframs-modules.j2
   dest: /etc/initramfs-tools/modules
   owner: root
   group: root
   mode: 0644
   backup: yes
  register: initframs_results

# then update initframs file
- name: update initframs
  command: update-initramfs -u
  when: initframs_results.changed