---
# my desktop no longer has 2 gpu-s, so I can remove the gpu/vfio passthrough tasks
# i have an old desktop with an intel cpu & amd gpu yay
- name: install non-free software for desktop
  apt:
   name:
    - firmware-amd-graphics
    - xserver-xorg-video-amdgpu
    - intel-microcode
