---
- name: install non-free software for desktop
  apt:
   name:
    - firmware-amd-graphics
    - intel-microcode
    - unrar

- name: create vfio.conf for gpu pass through
  template:
   src: templates/vfio_gpu.j2
   dest: /etc/modprobe.d/vfio.conf
   owner: root
   group: root
   mode: 0644
  register: vfio_result
  notify: "update-initframs"

# Add vfio modules to initrd
# so vfio mod can grab the gpu in time before amdgpu
# buster requires adding softdep on vfio-pci
# otherwise system grabs the graphics controller for amdgpu
# while vfio-pci only grabs the sound card on the gpu
- name: Add vfio modules to initrd
  template:
   src: templates/initframs-modules.j2
   dest: /etc/initramfs-tools/modules
   owner: root
   group: root
   mode: 0644
  register: initframs_results
  notify: "update-initframs"
