---
- name: install non-free software
  apt:
   name: "{{ packages }}"
  vars:
   packages:
   # laptop doesn't need this
   #- firmware-amd-graphics
   - intel-microcode
   - unrar

- name: install laptop battery saving tasks
  apt:
   name: "{{ packages }}"
  vars:
   packages:
   # laptop doesn't need this
   #- firmware-amd-graphics
   - tlp
   - powertop

- name: Create /etc/default/tlp template
  template:
    src: templates/tlp.j2
    dest: /etc/default/tlp
    mode: 0644
    owner: root
    group: root
    backup: yes   

# laptop battery saving tasks

# newer kernel for better battery life?
# doesn't seem to matter on this laptop

# configure some of the battery saving tasks

# 