---
- name: install non-free software
  apt:
   name: "{{ packages }}"
  vars:
   packages:
    - intel-microcode
    - unrar

- name: install laptop battery saving tasks
  apt:
   name: "{{ packages }}"
  vars:
   packages:
    - tlp
    - powertop

- name: Create /etc/default/tlp template
  template:
    src: templates/tlp.j2
    dest: /etc/default/tlp
    mode: 0644
    owner: root
    group: root
    backup: yes
