---
# i have an old laptop with an intel cpu yay
- name: Install non-free software for laptop
  ansible.builtin.apt:
   name:
    - intel-microcode

# either tlp or powertop used to cap intel on deb10 e1000e kmod to 100mbps instead of 1gbps
# - name: remove laptop battery saving packages
#  ansible.builtin.apt:
#   name:
#    - tlp
#    - powertop
#   state: absent

# - name: Remove
#  ansible.builtin.file:
#   path: /etc/default/tlp
#   state: absent
