---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: desktop_ct
    image: "${MOLECULE_DISTRO:-qwe1/docker-debian:11-nonfree-molecule}"
    privileged: true
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - desktop
  - name: laptop_ct
    image: "${MOLECULE_DISTRO:-qwe1/docker-debian:11-nonfree-molecule}"
    privileged: true
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - laptop
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      desktop:
        form_factor: desktop
        user: qwe
      laptop:
        form_factor: laptop
        user: qwe
scenario:
  name: default
