---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: desktop
    image: qwe1/debian9-contrib-nonfree:latest
    groups:
     - desktop
  - name: laptop
    image: qwe1/debian9-contrib-nonfree:latest
    groups:
     - laptop
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      desktop:
        form_factor: desktop
        user: qwe
      laptop:
        form_factor: laptop
        user: qwe
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
